package com.example.antennalab_v1.model

/*
########################################################################
FILE: PredictedPerformance.kt
PACKAGE: com.example.antennalab_v1.model
LAYER: Model

PURPOSE
Stores predicted real-world antenna behaviour after environmental
adjustments have been applied.

This sits AFTER the base antenna calculation but BEFORE results
are displayed to the user.

DESIGN GOALS
- Preserve the original calculated design
- Store prediction adjustments separately
- Allow future telemetry streaming
- Allow engineering dashboard analysis

FUTURE SYSTEMS
- SWR prediction engine
- tuning assistant
- live testing session streaming
- companion device telemetry
########################################################################
*/

data class PredictedPerformance(

    // Estimated SWR under current environmental conditions
    val predictedSWR: Double,

    // Estimated resonance shift in Hz caused by environment
    val resonanceShiftHz: Double,

    // Estimated radiation efficiency (0.0 – 1.0)
    val efficiencyEstimate: Double,

    // Quick human-readable summary for UI display
    val environmentSummary: String,

    // Warning messages generated by prediction engine
    val warnings: List<String> = emptyList()
)